# pylint: disable=E0602

SConscript('SConscript.boardloader', variant_dir='build/boardloader', duplicate=False)
SConscript('SConscript.boardloader_reflash_dev', variant_dir='build/boardloader_reflash_dev', duplicate=False)
SConscript('SConscript.bootloader', variant_dir='build/bootloader', duplicate=False)
SConscript('SConscript.firmware', variant_dir='build/firmware', duplicate=False)
SConscript('SConscript.unix', variant_dir='build/unix', duplicate=False)
