class PinResult:
    SUCCESS = 0
    USER_PIN_ENTERED = 1
    USER_PIN_FAILED = 2
    PASSPHRASE_PIN_ENTERED = 3
    PASSPHRASE_PIN_NO_MATCHED = 4
    USER_PIN_NOT_ENTERED = 5
    WIPE_CODE_ENTERED = 6
    PIN_SAME_AS_USER_PIN = 7
    PIN_SAME_AS_WIPE_CODE = 8
    PIN_PASSPHRASE_MAX_ITEMS_REACHED = 9
    PIN_PASSPHRASE_SAVE_FAILED = 10
    PIN_PASSPHRASE_READ_FAILED = 11
    PIN_FAILED = 12


class PinType:
    USER = 0
    USER_CHECK = 1
    USER_AND_PASSPHRASE_PIN = 2
    PASSPHRASE_PIN = 3
    PASSPHRASE_PIN_CHECK = 4
    MAX = 5
